local Lib = {}

function Lib:postInit()
	--[[print(Utils.pick({
		"Do you have a name, or can I just call you 'mine'?",
		"I seem to have lost my phone number. Can I have yours?",
		"You're so fine, you made me forget my pickup line.",
		"Did we go to school together? I could swear we had chemistry.",
		"Want a raisin? No? How about a date?",
		"What's your favorite drink? I'm asking so I know what to buy you on our first date.",
		"Have we met? Because you look exactly like my next boyfriend/girlfriend/partner.",
		"I never believed in love at first sight, but that's before I saw you.",
		"Do you have a map? Because I just got lost in your eyes.",
		"You owe me a drink. Because when I saw you, I dropped mine.",
		"They say nothing lasts forever, so will you be my nothing?",
		"Want to go outside for some fresh air? You took my breath away.",
		"If you were a song, you'd be the best single on the album.",
		"You remind me of a magnet because you sure are attracting me over here.",
		"I'm going to have to ask you to leave, you're making everyone else in here look bad.",
		"My parents told me not to talk to strangers, but I’ll make an exception for you.",
		"Are you a blender? 'Cause I want to put a baby in you.",
		"I like every bone in your body, including mine.",
		"Your first time to the family reunion?",
		"Does this rag smell like chloroform?",
		"Did it hurt when you fell from heaven? Is that how you fucked up your face?",
		"Damn girl, you shit with that ass?",
		"If you were a fart, I would clench my but cheeks so hard, that way I wouldn't ever have to let you go.",
		"Do you believe in love at first sight, or should I walk by again?",
		"I hope you know CPR, because you are taking my breath away.",
		"It's a good thing I have my library card, because I am totally checking you out.",
		"Are you a time traveler? Because I see you in my future.",
		"Your hand looks lonely. Can I hold it for you?",
		"I believe in following my dreams. Can I have your Instagram?",
		"Is your name Google? Because you're everything I've been searching for.",
		"Did the sun come out, or did you just smile at me?",
		"To quote the poet Katy Perry, \"You make me feel like I'm living a teenage dream.\"",
		"Hey, my name's Microsoft. Can I crash at your place tonight?",
		"Did your license get suspended for driving all those guys crazy?",
		"Are you a broom? Because you've swept me off my feet.",
		"Do you have a Band-Aid? I scraped my knee falling for you.",
		"I'm learning about important dates in history, wanna be one of them?",
		"Let's taco 'bout how amazing you are over tacos and margaritas next week.",
		"What do you call a string of people lifting a mozzarella cheese? A cheesy pickup line.",
		"Do you play soccer? Because you look like a keeper.",
		"How can I plan our wedding if I don’t have your number?",
		"You can delete the dating app now, I’m here.",
		"This might sound cheesy, but I think you're really grate.",
		"If you were a fruit, you'd be a \"fine-apple.\"",
		"Are you from Tennessee? Because you're the only 10 I see.",
		"Wanna touch my shirt? It's made of boyfriend/girlfriend/partner material.",
		"Are your parents bakers? Because you're a cutie pie.",
		"If you and I were socks, we'd make a great pair.",
		"Did it hurt when you fell from heaven?",
		"Aren't you tired? From running through my mind all day?",
		"If I could rearrange the alphabet, I'd put U and I together.",
		"Well, here I am! What are your other two wishes?",
		"Are you a parking ticket? You've got fine written all over you.",
	}))]]
end

return Lib