return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 20,
  nextobjectid = 76,
  properties = {
    ["border"] = "leaves",
    ["inside"] = true,
    ["light"] = "true",
    ["music"] = "hometown"
  },
  tilesets = {
    {
      name = "hometown_stuff",
      firstgid = 1,
      filename = "../../../../tilesets/hometown_stuff.tsx",
      exportfilename = "../../../../tilesets/hometown_stuff.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/hometown/townhall/mayorsoffice.png",
      id = 17,
      name = "bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/hometown/townhall/mayorsoffice_blinds.png",
      id = 19,
      name = "bg2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "spawn",
          type = "",
          shape = "point",
          x = 319.983,
          y = 441.262,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "noelle",
          type = "",
          shape = "point",
          x = 280,
          y = 342,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "comet",
          type = "",
          shape = "point",
          x = 352.813,
          y = 342.583,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "fountain",
          type = "",
          shape = "point",
          x = 320,
          y = 297,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "kris2",
          type = "",
          shape = "point",
          x = 286,
          y = 382.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "susie2",
          type = "",
          shape = "point",
          x = 355,
          y = 382.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "rubble1",
          type = "",
          shape = "point",
          x = 418,
          y = -3,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "rubble3",
          type = "",
          shape = "point",
          x = 195,
          y = -31,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "rubble4",
          type = "",
          shape = "point",
          x = 281,
          y = -65,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "rubble5",
          type = "",
          shape = "point",
          x = 116,
          y = -10,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "rubble2",
          type = "",
          shape = "point",
          x = 519,
          y = -15,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "kris",
          type = "",
          shape = "point",
          x = 319.98,
          y = 578,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "susie",
          type = "",
          shape = "point",
          x = 319.98,
          y = 611.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "comet2",
          type = "",
          shape = "point",
          x = 320,
          y = 295,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "comet3",
          type = "",
          shape = "point",
          x = 320,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 480,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 160,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 370.667,
          y = 400,
          width = 189.333,
          height = 121.976,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 400,
          width = 188,
          height = 120.6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 160,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 218.827,
          y = 194.742,
          width = 202.312,
          height = 61.9322,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 294.522,
          y = 258.051,
          width = 49.5457,
          height = 50.2339,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 283.333,
          y = 160,
          width = 70.6667,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 526.423,
          y = 161.024,
          width = 19.2678,
          height = 11.6983,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 501.332,
          y = 329.546,
          width = 58.6678,
          height = 70.4543,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 329.546,
          width = 61.4204,
          height = 70.4543,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 93,
          y = 160,
          width = 122,
          height = 27.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 23,
          name = "transition_extended",
          type = "",
          shape = "rectangle",
          x = 268.333,
          y = 480,
          width = 101.667,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["door"] = true,
            ["facing"] = "down",
            ["map"] = "hometown/townhall/hallway2",
            ["marker"] = "entry2"
          }
        },
        {
          id = 25,
          name = "npc",
          type = "",
          shape = "point",
          x = 320.216,
          y = 209.615,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "comet_lw",
            ["cond"] = "Game.chapter == 5",
            ["cutscene"] = "hometown/townhall.comet",
            ["sprite"] = "desk"
          }
        },
        {
          id = 29,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 120,
          width = 38.6667,
          height = 56.6667,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "hometown/townhall.trash2"
          }
        },
        {
          id = 31,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 294.667,
          y = 227.667,
          width = 50,
          height = 79.3334,
          rotation = 0,
          visible = true,
          properties = {
            ["cond"] = "Game.chapter == 5",
            ["cutscene"] = "hometown/townhall.chair2"
          }
        },
        {
          id = 32,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 93.5,
          y = 120,
          width = 110.667,
          height = 68.8334,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "hometown/townhall.drawers"
          }
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84.6667,
          y = 394,
          width = 56,
          height = 100,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 500,
          y = 393.667,
          width = 56,
          height = 100,
          rotation = 0,
          gid = 33,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 215.667,
          y = 258,
          width = 208,
          height = 88,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 293,
          y = 309,
          width = 52,
          height = 84,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {
            ["cond"] = "Game.chapter == 5"
          }
        },
        {
          id = 63,
          name = "npc",
          type = "",
          shape = "point",
          x = 382.5,
          y = 188,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "comet_lw",
            ["cond"] = "Game.chapter == 6",
            ["cutscene"] = "hometown/townhall.nosusie",
            ["facing"] = "up"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "paths",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 26,
          name = "comet_path",
          type = "",
          shape = "polyline",
          x = 360,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = -7, y = 22 },
            { x = 120, y = 22 },
            { x = 120, y = -80 },
            { x = 80, y = -80 },
            { x = 79.875, y = -110.75 },
            { x = -39.5152, y = -111.03 }
          },
          properties = {}
        },
        {
          id = 35,
          name = "noelle_path",
          type = "",
          shape = "polyline",
          x = 279.383,
          y = 342.691,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 0.688135, y = 39.2237 },
            { x = 14.4508, y = 39.2237 },
            { x = 14.4508, y = 94.9626 }
          },
          properties = {}
        },
        {
          id = 70,
          name = "comet_path2",
          type = "",
          shape = "polyline",
          x = 382.5,
          y = 188.5,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 78, y = 0 },
            { x = 57.5, y = 106.5 },
            { x = -62, y = 123.5 }
          },
          properties = {}
        }
      }
    }
  }
}
