return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 36,
  properties = {
    ["border"] = "leaves",
    ["inside"] = true,
    ["light"] = "true",
    ["music"] = "hometown",
    ["name"] = "High School Classroom"
  },
  tilesets = {
    {
      name = "school_interior",
      firstgid = 1,
      filename = "../../../../tilesets/school_interior.tsx",
      exportfilename = "../../../../tilesets/school_interior.lua"
    },
    {
      name = "hometown_stuff",
      firstgid = 1756,
      filename = "../../../../tilesets/hometown_stuff.tsx",
      exportfilename = "../../../../tilesets/hometown_stuff.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 0,
        0, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 0,
        0, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 0,
        0, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 0,
        0, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 0,
        0, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 0,
        0, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 0,
        0, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 0,
        0, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 0,
        0, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 0,
        0, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 0,
        0, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 172.501,
          width = 186.11,
          height = 27.4986,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 137.75,
          y = 243.5,
          width = 73.6667,
          height = 21.5833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276.5,
          y = 242.333,
          width = 75.9167,
          height = 22.5833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 413.5,
          y = 243.5,
          width = 73.6667,
          height = 22.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 413.5,
          y = 304.75,
          width = 73.6667,
          height = 23.0833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 277.583,
          y = 304.667,
          width = 73.6667,
          height = 22.8333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 137.917,
          y = 303.75,
          width = 73.6667,
          height = 23.0833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 277.5,
          y = 368.333,
          width = 73.6667,
          height = 22.5833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 137.583,
          y = 367.667,
          width = 73.6667,
          height = 23.5833,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 369.5,
          width = 73.6667,
          height = 22.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 569,
          y = 142,
          width = 40,
          height = 295.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 34,
          y = 141,
          width = 40,
          height = 298.666,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 75.3333,
          y = 436.667,
          width = 492.667,
          height = 43.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 76,
          y = 43,
          width = 396.667,
          height = 98.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 539.666,
          y = 47,
          width = 30.667,
          height = 95.3333,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 16,
          name = "spawn",
          type = "",
          shape = "point",
          x = 160,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "entry",
          type = "",
          shape = "point",
          x = 506,
          y = 196,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 472.25,
          y = 73,
          width = 66,
          height = 63.25,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "hometown/school/lobby",
            ["marker"] = "entry3"
          }
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200.121,
          y = 214,
          width = 188,
          height = 88,
          rotation = 0,
          gid = 1756,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136.25,
          y = 286,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276,
          y = 286,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 412,
          y = 286.25,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 137.036,
          y = 304.316,
          width = 73.6667,
          height = 18.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276.536,
          y = 304.149,
          width = 73.6667,
          height = 18.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 413.536,
          y = 305.316,
          width = 73.6667,
          height = 18.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136.18,
          y = 347.483,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276.002,
          y = 348.005,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 412.036,
          y = 348.066,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 137.055,
          y = 368.24,
          width = 73.6667,
          height = 18.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276.555,
          y = 368.073,
          width = 73.6667,
          height = 18.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 413.555,
          y = 369.24,
          width = 73.6667,
          height = 18.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 136.018,
          y = 411.998,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 276.052,
          y = 412.03,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 412.016,
          y = 411.99,
          width = 78,
          height = 56,
          rotation = 0,
          gid = 1758,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/hometown/school/torielclass_sunsetoverlay.png",
      id = 5,
      name = "overlay",
      class = "",
      visible = true,
      opacity = 0.48,
      offsetx = 76,
      offsety = 44,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
